### ISSUE TITLE
Support more decompression types

### ISSUE THREAD

**Issue by digitaldogsbody** [digitaldogsbody/mingulay#11]
The decision to use a `bool` to indicate DEFLATE usage or not was because that is the most common compression method used in zip files.

However, PHP also has a filter for bzip2 (https://www.php.net/manual/en/filters.compression.php) and that can be used in Zip files as well (https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT section 4.4.5), so we could perhaps consider changing the signature of `SeekerInterface::getStream` to accept the compression method straight from the file header, instead of parsing it in the ZipRangeReader library.

This would move responsibility for throwing `UnsupportedCompression` to the Seekers, but this is maybe a good thing as it will allow for differing levels of support depending on the Seeker, as well as extensibility in the future if we try to support more compression types.

The opposite side to this coin is that this might be such a rare use-case that the work to implement outweighs the potential benefits.

**Comment by DiegoPino** [comment]
@digitaldogsbody I do like the idea of using it from the file header. Do we get that info from the initial parsing? Means Central Directory v/s the actual payload might have different compressions? Or if bzip2/all is bzip2?

**Comment by DiegoPino** [comment]
Another option is to use attempt. try with Deflat/if that does not work go with another/etc. From more common to less common. Not sure if that is great (or a terrible idea)

**Comment by digitaldogsbody** [comment]
> @digitaldogsbody I do like the idea of using it from the file header. Do we get that info from the initial parsing? Means Central Directory v/s the actual payload might have different compressions? Or if bzip2/all is bzip2?

In theory, the Central Directory Records should contain identical information to the respective Local File Header records (although the CDR has a couple of extra fields per file) - see also the comment on the PR about maybe skipping the LFH if we trust the CDR: https://github.com/digitaldogsbody/mingulay/pull/9#discussion_r976970630

We do grab the compression data from the Central Directory Records when we parse them (`vcompression` in the unpack string), but we don't do anything with it at that point.

https://github.com/digitaldogsbody/mingulay/blob/main/src/ZipRangeReader.php#L194-L199

When `::getStream` is called, we read the relevant Local File Header (primarily to determine the "true" offset of the compressed data stream, since the CDR only gives us the offset of the variable-length LFH), and at that point we parse out the compression bytes again and that's what gets passed to `::getStream`: https://github.com/digitaldogsbody/mingulay/blob/1_add_get_stream/src/ZipRangeReader.php#L273-L279

Different files in the Zip can be compressed with different methods (for an example see `test/fixtures/multiple-files.zip`, where LICENSE is compressed with DEFLATE (and so has `0x0800` in the compression bytes), but README.md is not compressed (probably because too small?), and so it has `0x0000` in the compression bytes in the headers.

**Comment by digitaldogsbody** [comment]
> Another option is to use attempt. try with Deflat/if that does not work go with another/etc. From more common to less common. Not sure if that is great (or a terrible idea)

I think this is more tricky, since the filter is applied when the stream is read, so whether or not decompression with an individual method was successful would only be known by the end user after reading the whole file (maybe sooner if they know some content in the early bytes to test against - otherwise you have to get the whole thing and compare the CRC).

My expectation is that most extant zip file utilities rely on the compression bytes to determine how to decompress a given file, so we should be ok doing the same,
